server:
  port: 6005
spring:
  application:
    name: warn-server
  datasource:
    url: jdbc:mysql://localhost:3306/zyv1
    username: root
    password: 200034
  rabbitmq:
    port: 5672
    username: guest
    password: 200034
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

