server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: database-manager
          uri: lb://DATABASE-MANAGER
          predicates:
            - Path=/databasemanager/**
#          filters:
#            - StripPrefix=1
        - id: database-conn
          uri: lb://DATABASE-CONN
          predicates:
            - Path=/databaseconn/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

