server:
  port: 6001
spring:
  application:
    name: database-manager
  datasource:
    url: jdbc:mysql://localhost:3306/zyv1
    username: root
    password: 200034
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true